server:
  forward-headers-strategy: framework
  port: 8081
  servlet:
    session:
      timeout: 7d

spring:
  application:
    name: api-server
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:10354

  elasticsearch:
    uris: http://s4.java21.net:9200
    username: elastic
    password: nhnacademy123!
    ssl:
      verification-mode: none

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  session:
    redis:
      flush-mode: on_save

  cache:
    type: redis
    redis:
      time-to-live: 600000

  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000

  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      max-total: 30
      min-idle: 5
      max-idle: 15
      max-wait: 10000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs: 5000
      min-evictable-idle-time: 60000
      remove-abandoned-on-borrow: true
      remove-abandoned-timeout: 60

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10351/eureka/

logging:
  level:
    root: INFO
    org.apache.commons.dbcp2: DEBUG
    store.bookscamp.api: INFO
    org.springframework.web.reactive.function.client: WARN
    reactor.netty.http.client: WARN

elasticsearch:
  index:
    name: bookscamp-dev
