server:
  forward-headers-strategy: framework
  port: 8081
  servlet:
    session:
      timeout: 7d

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-server

  profiles:
    # Config Client에서 profile=dev로 호출할 거라 여기 active는 굳이 안 써도 되지만,
    # 쓰고 싶으면 주석 풀어서 사용
    # active: dev
    group:
      dev: dev

  elasticsearch:
    uris: http://s4.java21.net:9200
    username: elastic
    password: nhnacademy123!
    ssl:
      verification-mode: none

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  session:
    redis:
      flush-mode: on_save

  cache:
    type: redis
    redis:
      time-to-live: 600000

  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://s4.java21.net:13306/project_be11_team3_dev
    username: project_be11_team3
    password: ${PASSWORD}

    dbcp2:
      initial-size: 5
      max-total: 30
      min-idle: 5
      max-idle: 15
      max-wait: 10000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs: 5000
      min-evictable-idle-time: 60000
      remove-abandoned-on-borrow: true
      remove-abandoned-timeout: 60

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234

    listener:
      simple:
        auto-startup: false            # ★ dev에서는 리스너 안 띄움
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000
      direct:
        auto-startup: false

  data:
    redis:
      host: localhost
      port: 6379

aladin:
  base-url: https://www.aladin.co.kr/ttb/api
  ttb-key: ttbtvsqyfzvpj1722001
  output: js
  version: "20131101"

springdoc:
  api-docs:
    path: /bookscamp
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

google:
  gemini:
    api-key: AIzaSyBPqaTSQWhG4sRLVcTfk6v5VvC_Goyjobc

logging:
  level:
    root: INFO
    org.apache.commons.dbcp2: DEBUG
    store.bookscamp.api: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

elasticsearch:
  index:
    name: bookscamp-dev
