# =========================
# front-prod.yml (Config Repo)
# =========================

spring:
  application:
    name: front

  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  session:
    redis:
      flush-mode: on_save

  cache:
    type: redis
    redis:
      time-to-live: 600000

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: FULL

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 331

logging:
  level:
    feign.Logger: DEBUG
    store.bookscamp.front.book.feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG

# ===== API 서버 / Gateway prod 환경 =====
app:
  api:
    prefix: /gateway

# front는 eureka 미사용, gateway로만 호출
gateway:
  base-url: http://localhost:10352

# ===== MinIO 설정 (prod도 동일 사용) =====
minio:
  # 내부 통신용 (SDK)
  url: http://storage.java21.net:8000
  # 브라우저 노출용 (이미지 URL 반환용)
  public-url: https://bookscamp.store
  access-key: EvJ2FP8gy27lDYolEWGQ
  secret-key: h9uzw85pZPDchOTHzslEOUlNd5cDPFLQnJCofZfH
  bucket:
    book: bookscamp-book-image
    review: bookscamp-review-image
    package: bookscamp-package-image

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: BASIC
